### PR TITLE
Update to version 0.3.0

### PR DESCRIPTION
**Pull request by awvwgk**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #9

### CODE REVIEW

**Comment by aradi** [comment]
@conda-forge-admin, please rerender

**Comment by aradi** [comment]
@awvwgk Sorry, I didn't realize, that you are pushing here now. I won't interfere, let me know, if you managed to get it work.

**Comment by awvwgk** [comment]
Needs rebuild of whole dependency stack, looks like we got the Fortran ABI messed up again.

**Comment by awvwgk** [comment]
Still an issue with the module ABI for OSX/Arm64. Maybe worth to just skip this platform for now?

**Pull request merged**
